# Generated by Django 4.2.7 on 2023-11-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seaareaforecastmetie',
            options={'verbose_name_plural': 'sea area forecasts met ie'},
        ),
    ]
