# Generated by Django 4.2.7 on 2023-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0002_alter_seaareaforecastmetie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceurl',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sourceformat',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
