# Generated by Django 4.2.7 on 2023-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0004_seaareaforecastmet_weatherforecastcoast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetOceanBuoyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EightHourlyID', models.IntegerField()),
                ('MMSI', models.IntegerField()),
                ('AverageWindSpeed', models.IntegerField()),
                ('GustSpeed', models.IntegerField()),
                ('WindDirection', models.IntegerField()),
                ('WindGustDirection', models.IntegerField()),
                ('AirTemperature', models.FloatField()),
                ('RelativeHumidity', models.IntegerField()),
                ('DewPoint', models.FloatField()),
                ('AirPressure', models.IntegerField()),
                ('PressureTendency', models.IntegerField()),
                ('HorizVisibility', models.FloatField()),
                ('WaterLevel', models.FloatField()),
                ('WaterLevelTrend', models.IntegerField()),
                ('SurfaceCurrentSpeed', models.IntegerField()),
                ('SurfaceCurrentDirection', models.IntegerField()),
                ('CurrentSpeed2', models.IntegerField()),
                ('CurrentDirection2', models.IntegerField()),
                ('MeasurementDepth2', models.IntegerField()),
                ('CurrentSpeed3', models.IntegerField()),
                ('CurrentDirection3', models.IntegerField()),
                ('MeasurementDepth3', models.IntegerField()),
                ('WaveHeight', models.FloatField()),
                ('WavePeriod', models.IntegerField()),
                ('WaveDirection', models.IntegerField()),
                ('SwellHeight', models.FloatField()),
                ('SwellPeriod', models.IntegerField()),
                ('SwellDirection', models.IntegerField()),
                ('SeaState', models.IntegerField()),
                ('WaterTemperature', models.FloatField()),
                ('Precipitation', models.IntegerField()),
                ('Salinity', models.FloatField()),
                ('Ice', models.CharField()),
                ('DateTransmitted', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'met ocean buoy data',
            },
        ),
    ]
