# Generated by Django 4.2.7 on 2023-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0006_alter_metoceanbuoydata_airpressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherBuoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mmsi', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'weather buoys',
            },
        ),
    ]
