# Generated by Django 4.2.7 on 2023-12-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0008_alter_sourceurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrishLightsBuoyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('CallSign', models.CharField(max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('AtmosphericPressure', models.FloatField(blank=True, null=True)),
                ('WindDirection', models.FloatField(blank=True, null=True)),
                ('WindSpeed', models.FloatField(blank=True, null=True)),
                ('GustSpeed', models.FloatField(blank=True, null=True)),
                ('WaveHeight', models.FloatField(blank=True, null=True)),
                ('WavePeriod', models.FloatField(blank=True, null=True)),
                ('MeanWaveDirection', models.FloatField(blank=True, null=True)),
                ('Hmax', models.FloatField(blank=True, null=True)),
                ('AirTemperature', models.FloatField(blank=True, null=True)),
                ('DewPoint', models.FloatField(blank=True, null=True)),
                ('SeaTemperature', models.FloatField(blank=True, null=True)),
                ('salinity', models.FloatField(blank=True, null=True)),
                ('RelativeHumidity', models.FloatField(blank=True, null=True)),
                ('SprTp', models.FloatField(blank=True, null=True)),
                ('ThTp', models.FloatField(blank=True, null=True)),
                ('Tp', models.FloatField(blank=True, null=True)),
                ('QC_Flag', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'irish lights buoy data',
            },
        ),
    ]
