# Generated by Django 4.2.8 on 2023-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0009_irishlightsbuoydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IrishLightsBuoyData',
            new_name='MetIeBuoyData',
        ),
    ]
