# Generated by Django 4.2.8 on 2023-12-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0010_rename_irishlightsbuoydata_metiebuoydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metiebuoydata',
            old_name='GustSpeed',
            new_name='Gust',
        ),
    ]
