# Generated by Django 4.2.8 on 2023-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0012_seaareaforecastmet_swell_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecastcoast',
            name='area',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='weatherforecastcoast',
            name='visibility',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='weatherforecastcoast',
            name='wind',
            field=models.CharField(max_length=600),
        ),
    ]
