# Generated by Django 4.2.8 on 2023-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata', '0013_alter_weatherforecastcoast_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metiebuoydata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metiebuoydata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metiebuoydata',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
